# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-27 20:23
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user_interface', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='admin_id',
            field=models.UUIDField(default=uuid.UUID('b9f74ffa-31fc-11e8-bdf5-0242ac120003'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='autrecharge',
            name='autre_charge_id',
            field=models.UUIDField(default=uuid.UUID('b9f92e42-31fc-11e8-bdf5-0242ac120003'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_id',
            field=models.UUIDField(default=uuid.UUID('b9f76e68-31fc-11e8-bdf5-0242ac120003'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='conducteur',
            name='conducteur_id',
            field=models.UUIDField(default=uuid.UUID('b9f85efe-31fc-11e8-bdf5-0242ac120003'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='courbedediversitee',
            name='courbe_de_diversite_id',
            field=models.UUIDField(default=uuid.UUID('b9f90d5e-31fc-11e8-bdf5-0242ac120003'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='etude',
            name='etude_id',
            field=models.UUIDField(default=uuid.UUID('b9f7946a-31fc-11e8-bdf5-0242ac120003'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='logement',
            name='logement_id',
            field=models.UUIDField(default=uuid.UUID('b9f8a77e-31fc-11e8-bdf5-0242ac120003'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='noeud',
            name='noeud_id',
            field=models.UUIDField(default=uuid.UUID('b9f8878a-31fc-11e8-bdf5-0242ac120003'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='penteoriginedediversitee',
            name='pente_origine_diversite_id',
            field=models.UUIDField(default=uuid.UUID('b9f91e2a-31fc-11e8-bdf5-0242ac120003'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transformateur',
            name='transformateur_id',
            field=models.UUIDField(default=uuid.UUID('b9f8ddfc-31fc-11e8-bdf5-0242ac120003'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='typedechauffage',
            name='type_chauffage_id',
            field=models.UUIDField(default=uuid.UUID('b9f7caf2-31fc-11e8-bdf5-0242ac120003'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='typedeconducteur',
            name='type_conducteur_id',
            field=models.UUIDField(default=uuid.UUID('b9f7de70-31fc-11e8-bdf5-0242ac120003'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='typedelogement',
            name='type_logement_id',
            field=models.UUIDField(default=uuid.UUID('b9f8164c-31fc-11e8-bdf5-0242ac120003'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='typedetransformateur',
            name='type_transformateur_id',
            field=models.UUIDField(default=uuid.UUID('b9f82628-31fc-11e8-bdf5-0242ac120003'), primary_key=True, serialize=False),
        ),
    ]
