# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-30 18:46
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user_interface', '0005_auto_20180423_1341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='admin_cout_perte_puissance',
            new_name='admin_cout_pertes_puissance',
        ),
        migrations.RenameField(
            model_name='admin',
            old_name='admin_temp_ambiance_pte_a',
            new_name='admin_temp_ambiante_pte_a',
        ),
        migrations.RenameField(
            model_name='admin',
            old_name='admin_temp_ambiance_pte_s',
            new_name='admin_temp_ambiante_pte_s',
        ),
        migrations.AlterField(
            model_name='admin',
            name='admin_id',
            field=models.UUIDField(default=uuid.UUID('b7d0fb3a-4ca6-11e8-a9c7-0242ac120003'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='autrecharge',
            name='autre_charge_id',
            field=models.UUIDField(default=uuid.UUID('b7d2a3b8-4ca6-11e8-a9c7-0242ac120003'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_id',
            field=models.UUIDField(default=uuid.UUID('b7d11534-4ca6-11e8-a9c7-0242ac120003'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='conducteur',
            name='conducteur_id',
            field=models.UUIDField(default=uuid.UUID('b7d1df64-4ca6-11e8-a9c7-0242ac120003'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='courbedediversitee',
            name='courbe_de_diversite_id',
            field=models.UUIDField(default=uuid.UUID('b7d28176-4ca6-11e8-a9c7-0242ac120003'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='etude',
            name='etude_id',
            field=models.UUIDField(default=uuid.UUID('b7d13528-4ca6-11e8-a9c7-0242ac120003'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='logement',
            name='logement_id',
            field=models.UUIDField(default=uuid.UUID('b7d22fd2-4ca6-11e8-a9c7-0242ac120003'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='noeud',
            name='noeud_id',
            field=models.UUIDField(default=uuid.UUID('b7d210f6-4ca6-11e8-a9c7-0242ac120003'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='penteoriginedediversitee',
            name='pente_origine_diversite_id',
            field=models.UUIDField(default=uuid.UUID('b7d29170-4ca6-11e8-a9c7-0242ac120003'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transformateur',
            name='transformateur_id',
            field=models.UUIDField(default=uuid.UUID('b7d2585e-4ca6-11e8-a9c7-0242ac120003'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='typedechauffage',
            name='type_chauffage_id',
            field=models.UUIDField(default=uuid.UUID('b7d16520-4ca6-11e8-a9c7-0242ac120003'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='typedeconducteur',
            name='type_conducteur_id',
            field=models.UUIDField(default=uuid.UUID('b7d172fe-4ca6-11e8-a9c7-0242ac120003'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='typedelogement',
            name='type_logement_id',
            field=models.UUIDField(default=uuid.UUID('b7d1a1d4-4ca6-11e8-a9c7-0242ac120003'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='typedetransformateur',
            name='type_transformateur_id',
            field=models.UUIDField(default=uuid.UUID('b7d1cd80-4ca6-11e8-a9c7-0242ac120003'), primary_key=True, serialize=False),
        ),
    ]
