# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-01 22:04
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user_interface', '0006_auto_20180430_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='admin_r_source',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='admin',
            name='admin_x_source',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='admin',
            name='admin_id',
            field=models.UUIDField(default=uuid.UUID('adf511f6-4d8b-11e8-84dd-0242ac120003'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='admin',
            name='admin_r0_cond_mt_a',
            field=models.FloatField(default=0.357),
        ),
        migrations.AlterField(
            model_name='admin',
            name='admin_r0_cond_mt_s',
            field=models.FloatField(default=0.392),
        ),
        migrations.AlterField(
            model_name='admin',
            name='admin_r0_depart_mt',
            field=models.FloatField(default=0.0953),
        ),
        migrations.AlterField(
            model_name='admin',
            name='admin_r1_cond_mt_a',
            field=models.FloatField(default=0.104),
        ),
        migrations.AlterField(
            model_name='admin',
            name='admin_r1_cond_mt_s',
            field=models.FloatField(default=0.098),
        ),
        migrations.AlterField(
            model_name='admin',
            name='admin_r1_depart_mt',
            field=models.FloatField(default=0.0537),
        ),
        migrations.AlterField(
            model_name='admin',
            name='admin_x0_cond_mt_a',
            field=models.FloatField(default=1.313),
        ),
        migrations.AlterField(
            model_name='admin',
            name='admin_x0_cond_mt_s',
            field=models.FloatField(default=0.107),
        ),
        migrations.AlterField(
            model_name='admin',
            name='admin_x0_depart_mt',
            field=models.FloatField(default=3.8125),
        ),
        migrations.AlterField(
            model_name='admin',
            name='admin_x1_cond_mt_a',
            field=models.FloatField(default=0.395),
        ),
        migrations.AlterField(
            model_name='admin',
            name='admin_x1_cond_mt_s',
            field=models.FloatField(default=0.247),
        ),
        migrations.AlterField(
            model_name='admin',
            name='admin_x1_depart_mt',
            field=models.FloatField(default=1.324),
        ),
        migrations.AlterField(
            model_name='autrecharge',
            name='autre_charge_id',
            field=models.UUIDField(default=uuid.UUID('adf6f7aa-4d8b-11e8-84dd-0242ac120003'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_id',
            field=models.UUIDField(default=uuid.UUID('adf52dee-4d8b-11e8-84dd-0242ac120003'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='conducteur',
            name='conducteur_id',
            field=models.UUIDField(default=uuid.UUID('adf646f2-4d8b-11e8-84dd-0242ac120003'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='courbedediversitee',
            name='courbe_de_diversite_id',
            field=models.UUIDField(default=uuid.UUID('adf6d95a-4d8b-11e8-84dd-0242ac120003'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='etude',
            name='etude_id',
            field=models.UUIDField(default=uuid.UUID('adf5504e-4d8b-11e8-84dd-0242ac120003'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='logement',
            name='logement_id',
            field=models.UUIDField(default=uuid.UUID('adf68c52-4d8b-11e8-84dd-0242ac120003'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='noeud',
            name='noeud_id',
            field=models.UUIDField(default=uuid.UUID('adf66fba-4d8b-11e8-84dd-0242ac120003'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='penteoriginedediversitee',
            name='pente_origine_diversite_id',
            field=models.UUIDField(default=uuid.UUID('adf6e814-4d8b-11e8-84dd-0242ac120003'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transformateur',
            name='transformateur_id',
            field=models.UUIDField(default=uuid.UUID('adf6b56a-4d8b-11e8-84dd-0242ac120003'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='typedechauffage',
            name='type_chauffage_id',
            field=models.UUIDField(default=uuid.UUID('adf5a10c-4d8b-11e8-84dd-0242ac120003'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='typedeconducteur',
            name='type_conducteur_id',
            field=models.UUIDField(default=uuid.UUID('adf5bd22-4d8b-11e8-84dd-0242ac120003'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='typedelogement',
            name='type_logement_id',
            field=models.UUIDField(default=uuid.UUID('adf60476-4d8b-11e8-84dd-0242ac120003'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='typedetransformateur',
            name='type_transformateur_id',
            field=models.UUIDField(default=uuid.UUID('adf63414-4d8b-11e8-84dd-0242ac120003'), primary_key=True, serialize=False),
        ),
    ]
