# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-07 14:13
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user_interface', '0009_auto_20180502_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='admin_fp_autre_pointe',
            field=models.FloatField(default=95.0),
        ),
        migrations.AddField(
            model_name='admin',
            name='admin_fp_eletrique_pointe',
            field=models.FloatField(default=99.5),
        ),
        migrations.AddField(
            model_name='admin',
            name='admin_fp_recovery_autre_pointe',
            field=models.FloatField(default=95.0),
        ),
        migrations.AddField(
            model_name='admin',
            name='admin_fp_recovery_electrique_ponte',
            field=models.FloatField(default=99.79),
        ),
        migrations.AddField(
            model_name='admin',
            name='admin_fq_autre_pointe',
            field=models.FloatField(default=31.22),
        ),
        migrations.AddField(
            model_name='admin',
            name='admin_fq_eletrique_pointe',
            field=models.FloatField(default=9.99),
        ),
        migrations.AddField(
            model_name='admin',
            name='admin_fq_recovery_autre_pointe',
            field=models.FloatField(default=31.22),
        ),
        migrations.AddField(
            model_name='admin',
            name='admin_fq_recovery_electrique_pointe',
            field=models.FloatField(default=6.51),
        ),
        migrations.AlterField(
            model_name='admin',
            name='admin_id',
            field=models.UUIDField(default=uuid.UUID('d47fb51e-5200-11e8-895d-0242ac120003'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='autrecharge',
            name='autre_charge_id',
            field=models.UUIDField(default=uuid.UUID('d4819352-5200-11e8-895d-0242ac120003'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_id',
            field=models.UUIDField(default=uuid.UUID('d47fe1ce-5200-11e8-895d-0242ac120003'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='conducteur',
            name='conducteur_id',
            field=models.UUIDField(default=uuid.UUID('d480cd32-5200-11e8-895d-0242ac120003'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='courbedediversitee',
            name='courbe_de_diversite_id',
            field=models.UUIDField(default=uuid.UUID('d4816eb8-5200-11e8-895d-0242ac120003'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='etude',
            name='etude_id',
            field=models.UUIDField(default=uuid.UUID('d4800014-5200-11e8-895d-0242ac120003'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='logement',
            name='logement_id',
            field=models.UUIDField(default=uuid.UUID('d48113a0-5200-11e8-895d-0242ac120003'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='noeud',
            name='noeud_id',
            field=models.UUIDField(default=uuid.UUID('d480f5d2-5200-11e8-895d-0242ac120003'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='penteoriginedediversitee',
            name='pente_origine_diversite_id',
            field=models.UUIDField(default=uuid.UUID('d4818146-5200-11e8-895d-0242ac120003'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transformateur',
            name='transformateur_id',
            field=models.UUIDField(default=uuid.UUID('d48141fe-5200-11e8-895d-0242ac120003'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='typedechauffage',
            name='type_chauffage_id',
            field=models.UUIDField(default=uuid.UUID('d48034ee-5200-11e8-895d-0242ac120003'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='typedeconducteur',
            name='type_conducteur_id',
            field=models.UUIDField(default=uuid.UUID('d480445c-5200-11e8-895d-0242ac120003'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='typedelogement',
            name='type_logement_id',
            field=models.UUIDField(default=uuid.UUID('d4807cf6-5200-11e8-895d-0242ac120003'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='typedetransformateur',
            name='type_transformateur_id',
            field=models.UUIDField(default=uuid.UUID('d480b658-5200-11e8-895d-0242ac120003'), primary_key=True, serialize=False),
        ),
    ]
