# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-07 14:48
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user_interface', '0010_auto_20180507_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='admin_fp_recovery_electrique_ponte',
        ),
        migrations.AddField(
            model_name='admin',
            name='admin_fp_recovery_electrique_pointe',
            field=models.FloatField(default=99.7878321393371),
        ),
        migrations.AddField(
            model_name='admin',
            name='admin_fp_recovery_electrique_pointe_hiver',
            field=models.FloatField(default=99.7878321393371),
        ),
        migrations.AddField(
            model_name='admin',
            name='admin_fq_electrique_pointe_hiver',
            field=models.FloatField(default=9.98749217771907),
        ),
        migrations.AddField(
            model_name='admin',
            name='admin_fq_recovery_electrique_pointe_hiver',
            field=models.FloatField(default=6.51064950150825),
        ),
        migrations.AlterField(
            model_name='admin',
            name='admin_fq_autre_pointe',
            field=models.FloatField(default=31.224989991992),
        ),
        migrations.AlterField(
            model_name='admin',
            name='admin_fq_recovery_autre_pointe',
            field=models.FloatField(default=31.224989991992),
        ),
        migrations.AlterField(
            model_name='admin',
            name='admin_fq_recovery_electrique_pointe',
            field=models.FloatField(default=6.51064950150825),
        ),
        migrations.AlterField(
            model_name='admin',
            name='admin_id',
            field=models.UUIDField(default=uuid.UUID('aa44a638-5205-11e8-8985-0242ac120003'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='autrecharge',
            name='autre_charge_id',
            field=models.UUIDField(default=uuid.UUID('aa468d36-5205-11e8-8985-0242ac120003'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_id',
            field=models.UUIDField(default=uuid.UUID('aa44d27a-5205-11e8-8985-0242ac120003'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='conducteur',
            name='conducteur_id',
            field=models.UUIDField(default=uuid.UUID('aa45c108-5205-11e8-8985-0242ac120003'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='courbedediversitee',
            name='courbe_de_diversite_id',
            field=models.UUIDField(default=uuid.UUID('aa4669be-5205-11e8-8985-0242ac120003'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='etude',
            name='etude_id',
            field=models.UUIDField(default=uuid.UUID('aa44f138-5205-11e8-8985-0242ac120003'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='logement',
            name='logement_id',
            field=models.UUIDField(default=uuid.UUID('aa461054-5205-11e8-8985-0242ac120003'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='noeud',
            name='noeud_id',
            field=models.UUIDField(default=uuid.UUID('aa45ef2a-5205-11e8-8985-0242ac120003'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='penteoriginedediversitee',
            name='pente_origine_diversite_id',
            field=models.UUIDField(default=uuid.UUID('aa467c1a-5205-11e8-8985-0242ac120003'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transformateur',
            name='transformateur_id',
            field=models.UUIDField(default=uuid.UUID('aa463f02-5205-11e8-8985-0242ac120003'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='typedechauffage',
            name='type_chauffage_id',
            field=models.UUIDField(default=uuid.UUID('aa45284c-5205-11e8-8985-0242ac120003'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='typedeconducteur',
            name='type_conducteur_id',
            field=models.UUIDField(default=uuid.UUID('aa453846-5205-11e8-8985-0242ac120003'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='typedelogement',
            name='type_logement_id',
            field=models.UUIDField(default=uuid.UUID('aa456ca8-5205-11e8-8985-0242ac120003'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='typedetransformateur',
            name='type_transformateur_id',
            field=models.UUIDField(default=uuid.UUID('aa45ab82-5205-11e8-8985-0242ac120003'), primary_key=True, serialize=False),
        ),
    ]
